# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: reciak <reciak@student.42vienna.com>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/05/22 21:15:03 by reciak            #+#    #+#              #
#    Updated: 2025/05/22 22:13:13 by reciak           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

.PHONY: alltests
alltests:
	@echo 'Not implemented yet beyond this dummy version...'
	
